spring:
  application:
    name: userregistration

  datasource:
    url: jdbc:h2:file:./data/usersdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
      
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog/liquibase-changelog.yaml

logging:
  level:
    root: INFO
    '[callaou.userregistration]': DEBUG
    '[org.springframework.data.web.config.SpringDataJackson3Configuration$PageModule$WarningLoggingModifier]': OFF
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr([%thread]){magenta} %clr(%-5level) %clr(%logger{36}){cyan} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log